### ISSUE TITLE
Font not with Slides

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/PyCon2016#2]
So the Aldo font in assets (also on S3) is not shipped with the slides, so unless it's installed, Arial is used and it doesn't work very well.

**Comment by justjess** [comment]
Right. You need Aldo :) It should be in the repo?



On May 28, 2016 at 7:25:49 PM, Benjamin Bengfort (notifications@github.com) wrote:

So the Aldo font in assets (also on S3) is not shipped with the slides, so unless it's installed, Arial is used and it doesn't work very well.

**Comment by lauralorenz** [comment]
Ok fixed in repo via https://github.com/DistrictDataLabs/PyCon2016/commit/88e676e67ba2001896f3795ca47bea3cff86a35f and also uploaded to s3
