### ISSUE TITLE
Missing corpora for the 2016 NLTK and Gensim talk

### ISSUE THREAD

**Issue by afk314** [DistrictDataLabs/PyCon2016#7]
Looks like the galactic corpus is missing from the repo?

**Comment by bbengfort** [comment]
@afk314, unfortunately, we could not push the corpus to the repo because they contain copyright material. There are a few sites you could potentially grab them though:

http://www.chakoteya.net/movies/

and 

http://www.imsdb.com/scripts/Star-Wars-A-New-Hope.html
